version: '3'
services:
  api:
    build: ./api-node-service/
    working_dir: /home/node/app
    ports: 
      - 8080:8080
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    volumes:
      - ./api-node-service:/home/node/app
    command: npm run dev
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 9600:3600
    environment:
      MYSQL_ROOT_PASSWORD: test123

  adminer:
    image: adminer
    ports:
      - 8888:8080